### ISSUE TITLE
启动后，页面无法显示，最新v2.1.0版本。报错如下，帮忙看下什么问题

### ISSUE THREAD

**Issue by zzf1208** [smartloli/kafka-eagle-bin#5]
[2022-06-22 11:17:05] ZkClient.Thread-7-EventThread - INFO  - zookeeper state changed (SyncConnected)
 [2022-06-22 11:17:05] ZKFactoryUtils.Thread-7 - ERROR - Get broker info for zookeeper has error, msg is 
 org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1001)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:677)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:673)
	at org.smartloli.kafka.eagle.common.util.ZKFactoryUtils.initKafkaMetaData(ZKFactoryUtils.java:58)
	at org.smartloli.kafka.eagle.web.controller.StartupListener$ContextSchema.initKafkaMetaData(StartupListener.java:77)
	at org.smartloli.kafka.eagle.web.controller.StartupListener$ContextSchema.run(StartupListener.java:73)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:118)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2366)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2393)
	at org.I0Itec.zkclient.ZkConnection.getChildren(ZkConnection.java:120)
	at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:680)
	at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:677)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:991)
	... 5 more
[2022-06-22 11:17:05] ZkEventThread.ZkClient-EventThread-69-10.200.5.10:2181,10.200.5.4:2181,10.200.5.15:2181 - INFO  - Terminate ZkClient event thread.
 [2022-06-22 11:17:05] ClientCnxn.Thread-7-SendThread(10.200.5.10:2181) - WARN  - An exception was thrown while closing send thread for session 0x1000087d0a50016.
 EndOfStreamException: Unable to read additional data from server sessionid 0x1000087d0a50016, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1280)
[2022-06-22 11:17:05] ZooKeeper.Thread-7 - INFO  - Session: 0x1000087d0a50016 closed
 [2022-06-22 11:17:05] ClientCnxn.Thread-7-EventThread - INFO  - EventThread shut down for session: 0x1000087d0a50016
 [2022-06-22 11:17:05] DispatcherServlet.main - INFO  - Completed initialization in 1062 ms

**Comment by zzf1208** [comment]
![image](https://user-images.githubusercontent.com/40556830/174936194-a09aa4b5-e2ca-44d5-8385-369347503199.png)

**Comment by zzf1208** [comment]
问题已解决，故关闭，是因为配置zk有问题
